# Generated by Django 4.1.4 on 2023-11-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0002_rename_first_name_performadoc_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformaDoc',
        ),
    ]
